// REPORT
export const CLEAR_STATE = 'CLEAR_STATE'
export const SET_CATEGORY = 'SET_CATEGORY'
export const SET_DESCRIPTION = 'SET_DESCRIPTION'
export const SET_EMAIL = 'SET_EMAIL'
export const SET_FIRST_NAME = 'SET_FIRST_NAME'
export const SET_IMAGE_1 = 'SET_IMAGE_1'
export const SET_IMAGE_2 = 'SET_IMAGE_2'
export const SET_LAST_NAME = 'SET_LAST_NAME'
export const SET_LATITUDE = 'SET_LATITUDE'
export const SET_LOCATION = 'SET_LOCATION'
export const SET_LONGITUDE = 'SET_LONGITUDE'
export const SET_PHONE = 'SET_PHONE'
export const SET_TRACKING_ID = 'SET_TRACKING_ID'
